version: "3.9"
services:
  frontend:
    build: ./frontend
    container_name: dokka-docker-frontend
    command: serve -s build -l 3000
    # not need with nginx
    # ports:
    #   - "3000:3000"
    restart: unless-stopped
  api:
    build: ./api
    container_name: dokka-docker-api
    command: npm run start
    restart: unless-stopped
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
      - HOST=http://dokka.com
      - MONGO_URL=mongodb://api_db:27017/api
      - AUTH_API_URL=http://auth:3002/api
    depends_on:
      - api_db

  auth:
    build: ./auth
    container_name: dokka-docker-auth
    command: npm run start
    restart: unless-stopped
    ports:
      - "3002:3002"
    environment:
      - PORT=3002
      - HOST=http://dokka.com
      - MONGO_URL=mongodb://auth_db:27017/auth
    depends_on:
      - auth_db

  api_db:
    image: mongo:6.0.4-jammy
    container_name: dokka-docker-api-db
    volumes:
      - mongo_api:/data/db

  auth_db:
    image: mongo:6.0.4-jammy
    container_name: dokka-docker-auth-db
    volumes:
      - mongo_auth:/data/db

  nginx:
    image: nginx:stable-alpine
    container_name: dokka-docker-nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf.prod:/etc/nginx/conf.d/nginx.conf
    depends_on:
      - frontend

volumes:
  mongo_api:
  mongo_auth:
